# Generated by cucumber-sinatra. (2011-08-02 17:30:14 +0800)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/imohe-filebrowser.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = IMohe::FileBrowser

class IMohe::FileBrowserWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  IMohe::FileBrowserWorld.new
end
